[project]
name = "timegrad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "scikit-learn>=1.7.1",
    "torch>=2.7.1",
]
